language: node_js
node_js:
  - "8.10"
  - "6.10"

before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi

script:
   - node --version
   - npm --version
   - grunt standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
